### ISSUE TITLE
Render issues with window buttons

### ISSUE THREAD

**Issue by jesusrp98** [gtk-flutter/libadwaita#29]
The window buttons look different compared to the demo provided by the Adwaita team.

Adwaita Demo App
![Screenshot from 2021-12-28 21-04-25](https://user-images.githubusercontent.com/8961959/147603166-e015e66c-a35c-444e-ad64-8ac05f2404da.png)

This package
![Screenshot from 2021-12-28 21-06-10](https://user-images.githubusercontent.com/8961959/147603169-345d4fbe-ead9-4b01-83a1-06b0f5136414.png)

I suggest implement those window buttons directly to this package, instead on relying on a third party package.

What do you think about this? I could take this issue if you think this could be beneficial for the package :)

**Comment by jesusrp98** [comment]
It seems that the `window_decoration` package to render those buttons on the Flutter implementation of Adwaita belongs to the same organization as this package.

Maybe we'd need to improve the current implementation of that package of the new libadwaita theme.

**Comment by prateekmedia** [comment]
@jesusrp98 Those are just svg in window_decoration package, just updating them with new ones would work.

**Comment by jesusrp98** [comment]
Would you be able to do that @prateekmedia ? Apart from the obious change in color, it seems that there are some issues regarding the actual svg render, that is not present in other window buttons, such as `yaru`.

**Comment by prateekmedia** [comment]
Will be fixed in next version.
