### ISSUE TITLE
Rework `AdwHeaderButton` using Material widgets

### ISSUE THREAD

**Issue by jesusrp98** [gtk-flutter/libadwaita#30]
Rather than using a simple `Container` for building header buttons, a simple material button without the 'ripple' effect could be used.

We could tweak the style of the material button to make it the same as the one implemented by the Adwaita team.

**Comment by MalcolmMielle** [comment]
Feel free to send in a PR for that change. Sounds good to me.

**Comment by jesusrp98** [comment]
After some work on this, I've decided that I'd pursue other fixes around the header buttons and other aspects of the UI, instead of reinventing this widget.

Expect a few PRs from my side in the coming days/weeks :)
