### ISSUE TITLE
Remove unofficial from title and README

### ISSUE THREAD

**Issue by MalcolmMielle** [gtk-flutter/libadwaita#34]
I'm thinking that the unofficial make it sound bad? Since everything is LGPLv3 that precision is not needed.

Maybe replacing

> Unofficial implementation of Libadwaita Widgets in Flutter.

with: 

> An implementation of Libadwaita Widgets in Flutter.

Is enough.

**Comment by prateekmedia** [comment]
Dart minimum description length is 120 for good score, So that will not count upto 120 I think.

**Comment by MalcolmMielle** [comment]
Dumb questions but:

* You mean 120 char?
* Can you point me to the sentence that is above 120 char and will go under 120 char with the change a propose? I will re-write it to take the 120char into account :).

**Comment by prateekmedia** [comment]
- yes
-- `An implementation of Libadwaita Widgets in Flutter.` is under 120 char(60 char only).

**Comment by MalcolmMielle** [comment]
I feel like I'm missing something, so, sorry in advance for being obtuse, hahaha.

Isn't `Unofficial implementation of Libadwaita Widgets in Flutter.` 59 chars, and `An implementation of Libadwaita Widgets in Flutter.` 51 chars? Are they not both under 120?

**Comment by prateekmedia** [comment]
Oops, Please ignore my last comments, The range is `60 to 180 characters`

**Comment by MalcolmMielle** [comment]
Ok what about `Libadwaita's widgets for Flutter. Following Gnome's human interface guidelines and available on (almost) all platforms.` ? It's 119 char. I'm opened to suggestions!

**Comment by prateekmedia** [comment]
I have changed the description in pubspec, README. If anything else is needed, then you can reopen the issue.
