### ISSUE TITLE
Pop-over menu is not rounded.

### ISSUE THREAD

**Issue by scotch-hub** [gtk-flutter/libadwaita#35]
The following picture shows that the pop-over menu doesn't have rounded corners on both of the top corners. This should be a relativly easy fix, so I'll try to dig in the source code!

![Screenshot from 2022-01-02 00-34-11](https://user-images.githubusercontent.com/73116038/147863114-47d0f218-7876-43bf-87ef-db9c472d3e0d.png)

Also, the animation for the pop-over tends to be quite laggy at times. Might open another issue related to that.

**Comment by MalcolmMielle** [comment]
Thanks for looking into the top rounded corners! I've actually struggled to create a similar pop-over and didn't have time to figure out how to round the top corners. It would be awesome if you could do it!

Look into [this file](https://github.com/gtk-flutter/libadwaita/blob/main/lib/src/internal/popover.dart), `PopOverClipper` is the class responsible for clipping the top arrow. That should be a good start!

**Comment by prateekmedia** [comment]
I have found this -> https://stackoverflow.com/questions/57028510/flutter-custom-clipper-radius, This might be related.

**Comment by prateekmedia** [comment]
Will be fixed in next version.
