### ISSUE TITLE
The header bar only registers every second double-click

### ISSUE THREAD

**Issue by scotch-hub** [gtk-flutter/libadwaita#36]
For example, whenever I try to drag the window from the header bar after having already dragged it, the double-click doesn't register.
This issue doesn't occur when I click on the header bar once in between the two double-clicks.
This is mostly related to the window_decoration package but I have yet to test it.

**Comment by prateekmedia** [comment]
Window decorations is only responsible for rendering the end window title bar buttons so it is not related to it.

**Comment by prateekmedia** [comment]
Can't reproduce the same on the latest version.
