### ISSUE TITLE
Multiple scrollbars in Avatar page

### ISSUE THREAD

**Issue by MalcolmMielle** [gtk-flutter/libadwaita#37]
When scrolling on the avatar page, I got it by this error:

```
Exception has occurred.
FlutterError (The provided ScrollController is currently attached to more than one ScrollPosition.
The Scrollbar requires a single ScrollPosition in order to be painted.
When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.)
```

@jesusrp98 could have a look at it since it seems related to your latest PR :)?

Otherwise, this error comes in pretty often when adding pages in the Adw example app. Is there any way we could restrict it so that it doesn't happen, e.g. by removing a scrollbar from AdwScaffold or something similar?

**Comment by jesusrp98** [comment]
I'll take a look at this issue.
