### ISSUE TITLE
Move color logic outside of libadwaita utils/colors into theme package

### ISSUE THREAD

**Issue by MalcolmMielle** [gtk-flutter/libadwaita#55]
For now, the colors used for avatars are hardcoded in `utils/colors.dart`. The color logic should be delegated to the theme (e.g. `yaru` or `adwaita`) and moved out of `libawaita`.

**Comment by prateekmedia** [comment]
Will yaru theme accept it?

**Comment by MalcolmMielle** [comment]
Maybe there is a way to do it. I'm not sure how.

**Comment by prateekmedia** [comment]
If you disagree, then I will reopen the issue. I am open for suggestions.

**Comment by MalcolmMielle** [comment]
Ok sounds good for now :)
