### ISSUE TITLE
How to use "libadwaita_bitsdojo"?

### ISSUE THREAD

**Issue by Ridhubharan** [gtk-flutter/libadwaita#67]
Instructions are not clear. Where am I supposed to put the following(as per https://github.com/gtk-flutter/libadwaita_plugins/tree/main/libadwaita_bitsdojo#usage)?
```
AdwHeaderBar.bitsdojo(
    appWindow: appWindow,
    ...
)
```
The 'headerbar' used in the 'AdwScaffold' widget is deprecated. (https://github.com/gtk-flutter/libadwaita_plugins/blob/main/libadwaita_bitsdojo/example/example.md)

**Comment by prateekmedia** [comment]
https://github.com/gtk-flutter/libadwaita#libadwaita_bitsdojo

**Comment by prateekmedia** [comment]
https://pub.dev/packages/libadwaita_bitsdojo/example

**Comment by Ridhubharan** [comment]
Like I said, The 'headerbar' used in the 'AdwScaffold' widget is deprecated and doesn't work. (https://pub.dev/packages/libadwaita_bitsdojo/example)

![image](https://user-images.githubusercontent.com/41824719/175766911-80d48c31-1d77-4d69-b772-0f2aed8e3f6b.png)
The code in the example creates two headerbars.

**Comment by prateekmedia** [comment]
Ok documentation needs to be updated, directly use actions and start parameter in the AdwScaffold instead of putting them in the headerbar.

**Comment by Ridhubharan** [comment]
I tried it too. Still it shows two headerbars.

![Screenshot from 2022-06-25 14-56-59](https://user-images.githubusercontent.com/41824719/175767525-3d735402-9d07-4638-901e-c5250a8df256.png)

![image](https://user-images.githubusercontent.com/41824719/175767477-63925ff9-0e08-4064-b1b8-85c4597e1f61.png)

**Comment by prateekmedia** [comment]
I think you are not following the bitsdojo's documentation for Linux dekstop, https://pub.dev/packages/bitsdojo_window#for-linux-apps

**Comment by Ridhubharan** [comment]
Yeah, you were right. Please mention this in https://pub.dev/packages/libadwaita_bitsdojo. Also, how to enable rounded corners?

**Comment by prateekmedia** [comment]
@Ridhubharan We don't control that, ask bitsdojo for that, I think there is an already open issue for that.
