### ISSUE TITLE
error adding dependency: libadwaita depends on libadwaita

### ISSUE THREAD

**Issue by augugusto** [gtk-flutter/libadwaita#72]
when I run 
`flutter pub add libadwaita`
i get 
`Because libadwaita depends on libadwaita, version solving failed.
pub finished with exit code 65`

If I add it to pubsec.yaml and then run
`flutter pub get`
i get
`Error on line 34, column 3 of pubspec.yaml: A package may not list itself as a dependency.`

I've looked at libadwaitas pubsec.yaml but I do not see it as it's own dependency

**Comment by prateekmedia** [comment]
What is your application name in pubspec?

-------- Original Message --------

**Comment by augugusto** [comment]
You know how you sometimes go to bed and realize you are an idiot as soon as you wake up? Since i was testing libadwaita i named my project libadwaita and then tried to add libadwaita as a dependency.

 I can't check right now but I bet that was the cause. Thanks for your time
