### ISSUE TITLE
License issues (incompatiblity with GPL)

### ISSUE THREAD

**Issue by theCapypara** [gtk-flutter/libadwaita#89]
Hello!
First sorry in advance if I just misunderstand the license, I have not worked with a MPL-2.0 project before.

It seems to me that the current license is incompatible with any (L)GPL license, due to the "Incompatible With Secondary Licenses" clause included in it. This applies to this and all the other packages licensed as MPL-2.0. 

See also: https://www.gnu.org/licenses/license-list.html and https://www.mozilla.org/en-US/MPL/2.0/FAQ/ (Q14)

Additionally even without this, the license is not compatible with GPLv3. Unfortunately I want to use this for a project licensed as GPLv3. Could you add an additional license to the packages that is compatible with GPLv3?

**Comment by prateekmedia** [comment]
Hi, we have chosen MPL-2.0 very carefully as we wanted a good alternative to LGPL. Now coming back to you query, MPL-2.0 is totally compatible with other licenses. Please see Q25 in FAQ's.
https://www.mozilla.org/en-US/MPL/2.0/FAQ/

In summary:
- If you include the full MPL 2.0 text without the per-file boilerplate, your code is still under the MPL 2.0 but not considered incompatible with other licenses.
- You need to actively use the Exhibit B boilerplate within individual files to trigger incompatibility.

So as we have not included any header of incompatible license or upgraded from MPL 1.1, this clause holds null and void, Thanks!

**Comment by prateekmedia** [comment]
I'm personally using this in PsTube and AppImage Pool application and these are GPL-3.0 projects too.

**Comment by theCapypara** [comment]
Ah okay, I thought the existence of the "Incompatible With Secondary Licenses" clause in the license file itself was already enough to mark it as incompatible. If this is not the case, it's fine! Thanks!
