### ISSUE TITLE
Check libadwaita gnome41 modifications

### ISSUE THREAD

**Issue by MalcolmMielle** [gtk-flutter/libadwaita#9]
Not an issue yet, but worth keeping an eye on the evolution of libadwaita since the [CSS color stylesheet will change](https://help.gnome.org/misc/release-notes/41.0/developers.html). I'm not sure yet what it will look like, but there are heated discussion on the topic, which might make the GnomeTheme parser obsolete.

**Comment by prateekmedia** [comment]
Yes, if we switch to GTK4 and libadwaita then it would help this plugin a lot as theming api would be simplified.
